server:
  port: 8081
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dingsai
  data:
    mongodb:
      database: dingsai
      authentication-database: admin
      uri: mongodb://root:123456@localhost:27017
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/src/main/resources/mapper/*Mapper.xml
